### PR TITLE
Add BeYourMarket

### PR DESCRIPTION
**Pull request by beyourmarket**
propose [BeYourMarket](https://github.com/beyourmarket/beyourmarket) - BeYourMarket is a peer-to-peer marketplace framework http://beyourmarket.com

### CODE REVIEW

**Comment by richlander** [comment]
@beyourmarket can you elaborate on how BeYourMarket fits as a .NET Developer project?

**Comment by kenyeung128** [comment]
@richlander BeYourMarket is an opensource framework based on asp.net mvc 5, c#, which is used for building a marketplace with 2 sided market like airBnb. It will help developer with much shorter time of development with a list of features, which can also be customized. I don't think there is such an open source framework in .net yet, so I hope it would be appreciated to be listed.

**Comment by beyourmarket** [comment]
@richlander would the explanation above be sufficient?

**Comment by richlander** [comment]
Sounds great! Thanks for building it.

**Comment by kenyeung128** [comment]
thanks @richlander :)

**Pull request merged**
