### PR TITLE
Update dotnet-developer-projects.md

### PR DESCRIPTION
**Pull request by tig**

### CODE REVIEW

**Comment by richlander** [comment]
@tig Looks like you have a set of deletions. Is that intentional?

**Comment by tig** [comment]
No. I think I did the merge incorrectly. I just added the Alexa stuff.

-cek
Sent from my mobile contraption. Expect typos, autocorrect errors, brevity, and dangerous driving.
________________________________

**Comment by richlander** [comment]
@tig Can you try again? I naturally cannot accept the commit in its current state.

**Comment by tig** [comment]
Yes. Next time im at my PC. Sorry.

-cek
Sent from my mobile contraption. Expect typos, autocorrect errors, brevity, and dangerous driving.
________________________________

**Comment by tig** [comment]
Closing due to my screw up.

**Pull request closed without merging**
