### PR TITLE
re-add ASPNET472CompatDoc

### PR DESCRIPTION
**Pull request by HongGit**
Re-add the ASP.NET 4.7.2 Compat Doc and incorporate feedbacks.

### CODE REVIEW

**Comment by HongGit** [comment]
@rpetrusha are you done with review?  Will you merge the PR to master?

**Comment by rpetrusha** [comment]
Yes, I'm done with the review, @HongGit. Before I merge, I just want to check whether this goes into the 4.7.1 branch or the 4.7.2 branch, and whether the reverted field should be present. I'll merge it sometime tomorrow.

**Comment by HongGit** [comment]
This should goto 4.7.2 branch.  Which reverted field are you referring to?

**Comment by mjrousos** [comment]
Yes, I think 4.7.2 is the right branch. Regarding the reverted field, I think Ron means this:

```json
### Version Introduced
4.6.1

### Version Reverted
4.7.2
```

Usually we use `Version Introduced` to be the first NetFX version that the breaking change is present in and in the unusual case that the change is undone later, we put that version in `Version Reverted`. In this case, I think the change that we're documenting is the switch from dataTypeAttribute:disableRegEx defaulting to false to, instead, defaulting to true.

Since that change (defaulting to true) is new in 4.7.2, I think that `Version Introduced` should be 4.7.2 and we can remove the Version Reverted section.

**Comment by rpetrusha** [comment]
I've made the changes that @mjrousos suggested, @HongGit, and I'll merge. Since this merges to the master branch, I'll open a new PR to delete it, and also open a new PR to merge it into the net472 branch.

**Pull request merged**
