### PR TITLE
Changed change category from retargeting to runtime

### PR DESCRIPTION
**Pull request by rpetrusha**
Also corrected casing and punctuation.

/cc @conniey @twsouthwick @mjrousos

### CODE REVIEW

**Comment by conniey** [comment]
To change this from retargeting to runtime, you have to leave the `Quirked` and `Build-time break` boxes unchecked. [BreakingChange.cs L66-72](https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability/BreakingChange.cs#L66-L72).  Is this correct @mjrousos?

**Comment by mjrousos** [comment]
Correct

**Comment by rpetrusha** [comment]
@Thanks, @conniey and @mjrousos. I've fixed it.

**Comment by conniey** [comment]
LGTM

**Pull request merged**
