### PR TITLE
Added 4.7 JIT issue

### PR DESCRIPTION
**Pull request by rpetrusha**
@brianrob, is there any additional detail that we can add here?

/cc @conniey, @mjrousos

### CODE REVIEW

**Comment by brianrob** [comment]
@rpetrusha, I can't say I familiar with this one.  Given it is a JIT issue, you probably want to run it by @RussKeldorph.

**Comment by rpetrusha** [comment]
Thanks, @brianrob. @RussKeldorph, is this correct, and can we add any additional detail?

**Comment by RussKeldorph** [comment]
@rpetrusha Per @briansull, this appears to be dotnet/coreclr#11508.

Are there other JIT bug fixes you're planning to note?  If not, how was this one selected for inclusion in this list?

**Comment by rpetrusha** [comment]
@RussKeldorph, yes, it is /dotnet/coreclr#11508. It's the only JIT bug fix I was planning to document; it was selected by the app compat team. Unless I've missed some, @PriyaPurkayastha?

**Comment by RussKeldorph** [comment]
@rpetrusha Ok, thanks.  To answer your earlier question, I think the best thing to do would be to add a link to dotnet/coreclr#11508, which should have as many details as we can provide.  In general, the same goes for other issues for which we have the information already available publicly on GitHub.

**Comment by rpetrusha** [comment]
OK. Thanks, @RussKeldorph.

**Pull request merged**
