### PR TITLE
Update dotnet-developer-projects.md

### PR DESCRIPTION
**Pull request by iancooper**
Added Brighter to the list of libraries

### CODE REVIEW

**Comment by richlander** [comment]
Sorry for the delay!

@iancooper - I see that there is an indent in your PR. Is that intentional?

**Comment by richlander** [comment]
Thoughts on this @iancooper?

**Comment by iancooper** [comment]
No not intentional. Let me fix that and resubmit the PR

**Comment by richlander** [comment]
Thanks @iancooper. Appreciated.

**Pull request closed without merging**
