### PR TITLE
Raygun Cross platform error reporting tool  updated in readme file

### PR DESCRIPTION
**Pull request by Apollo9999**
Raygun Cross platform error reporting tool  updated in readme file

### CODE REVIEW

**Comment by Apollo9999** [comment]
@microsoft-github-policy-service agree

**Review by terrajobst — CHANGES_REQUESTED** [review]
There are several Markdown files in this repository already that are meant to promote projects supporting .NET. Please integrate your list into those instead.

**Comment by Apollo9999** [comment]
Sir @terrajobst please respond

**Comment by Apollo9999** [comment]
New PR raised

**Pull request closed without merging**
