### PR TITLE
2 additional changes from 4.6.1 and 4.6.2

### PR DESCRIPTION
**Pull request by rpetrusha**
Documents two additional changes from 4.6.1 and 4.6.2.

/cc @mjrousos @twsouthwick @conniey

### CODE REVIEW

**Comment by richlander** [comment]
@rpetrusha can you run to bc-readme-gen tool to update the README as part of your PR? https://github.com/Microsoft/dotnet/tree/master/src/bc-readme-gen 

Can you make sure the titles start with the technology so that the sort in the README is good?

**Comment by rpetrusha** [comment]
@richlander, I've renamed one file and added the new README

**Comment by richlander** [comment]
I see. Please re-run again. The app expects that the .NET Framework version appears directly after the "Version Introduced" header. You can see that it is generating a bad readme w/no version. If you look at the README, it no longer makes sense. Please fix that @rpetrusha .

**Comment by rpetrusha** [comment]
@richlander, fixed. Sorry about that.

**Pull request merged**
