### PR TITLE
Added description of the LibGit2Sharp library

### PR DESCRIPTION
**Pull request by ckuhn203**

### CODE REVIEW

**Comment by richlander** [comment]
Thanks! "implmenetation" is spelled incorrectly. Can you fix that (and preferably squash)?

**Comment by ckuhn203** [comment]
Oops! Sure. Will do.

**Comment by ckuhn203** [comment]
@richlander spelling corrected and commits squashed.

**Comment by richlander** [comment]
Thanks @ckuhn203. Appreciated.

**Comment by ckuhn203** [comment]
You're welcome. Cheers!

**Pull request merged**
