### PR TITLE
Removing all rights reserved from MIT license

### PR DESCRIPTION
**Pull request by szarroug3**

### CODE REVIEW

**Comment by wujun4code** [comment]
why remove these words?

**Comment by szarroug3** [comment]
They're not part of the MIT license. https://opensource.org/licenses/MIT

**Comment by rpetrusha** [comment]
and also <https://microsoft.mit-license.org/>.

**Comment by rpetrusha** [comment]
Thanks for noticing this, @szarroug3. We'll merge your PR now.

**Pull request merged**
