### PR TITLE
Update the issue with the list of types potentially impacted

### PR DESCRIPTION
**Pull request by AlexGhiondea**
@vivmishra

### CODE REVIEW

**Comment by rpetrusha** [comment]
@AlexGhiondea, I made a few changes so that links would resolve properly. But this is intended to be an app compat topic, isn't it? If it is, it needs some required sections (which are in !Template.md),  For example:

## Scope
Major

### Version Introduced
4.7.1

### Source Analyzer Status
NotPlanned

And it also needs 

- [x] Quirked

- [ ] Build-time break

so that the migration tool knows what to do with it.

**Comment by rpetrusha** [comment]
Since this is a known issue rather than an app compat issue, @AlexGhiondea, ignore my comments.  I'll also undo some of my changes -- I don't think that linking is supported from known issues through \<xref:> or asset IDs.

**Comment by AlexGhiondea** [comment]
@vivmishra I don't understand what you are asking for.

**Comment by AlexGhiondea** [comment]
@rpetrusha anything else needed for this?

**Pull request merged**
